/// <reference types="cypress" />

describe("Subscription Form", () => {

    it("Checking inputs to be typeable and checking instructions and validation messages", () => {
        cy.visit('/')
        cy.contains('Subscription Form').should('be.visible')

        cy.get('#username').should('have.value', '')
        cy.get('#email').should('have.value', '')
        cy.get('#password').should('have.value', '')
        cy.get('#confirm-password').should('have.value', '')
        cy.get('#skills').should('have.value', 'Select...')
        cy.get('#skills').children().first().then(option1 => {expect(option1).to.be.selected})
        cy.get('#skills').children().first().should('have.text', 'Select...')
        cy.get('#checkbox').should('not.be.checked')

        cy.get('form > :nth-child(5)').should('not.be.visible')
        cy.get('form > :nth-child(9)').should('not.be.visible')
        cy.get('form > :nth-child(13)').should('not.be.visible')
        cy.get('form > :nth-child(16)').should('not.be.visible')
        cy.get('form > :nth-child(20)').should('not.be.visible')

        cy.contains('Valid Username').should('not.be.visible')
        cy.contains('Valid Email').should('not.be.visible')
        cy.contains('Valid Password').should('not.be.visible')
        cy.contains('Password confirmed').should('not.be.visible')
        cy.contains('A skill is selected').should('not.be.visible')

        cy.get('#info1').should('have.class', 'hideIns')
        cy.get('#done1').should('have.class', 'hide')
        cy.get('#info2').should('have.class', 'hideIns')
        cy.get('#done2').should('have.class', 'hide')
        cy.get('#info3').should('have.class', 'hideIns')
        cy.get('#done3').should('have.class', 'hide')
        cy.get('#done4').should('have.class', 'hide')
        cy.get('#info4').should('have.class', 'hideIns')
        cy.get('#done5').should('have.class', 'hide')

        // username element check
        cy.get('#username').click().focused()
        cy.get('#username').focus()
        cy.get('#info1').should('have.class', 'instructions')
        cy.get('#info1').should('not.have.class', 'hideIns')
        cy.get('#done1').should('have.class', 'hide')
        cy.get('#done1').should('not.have.class', 'show')
        cy.contains('Username Instructions').should('be.visible')
        cy.contains('Valid Username').should('not.be.visible')

        cy.get('#username').type('Mari')
        cy.get('#info1').should('have.class', 'instructions')
        cy.get('#info1').should('not.have.class', 'hideIns')
        cy.get('#done1').should('have.class', 'hide')
        cy.get('#done1').should('not.have.class', 'show')
        cy.contains('Username Instructions').should('be.visible')
        cy.contains('Valid Username').should('not.be.visible')

        cy.get('#username').clear().type('Maria')
        cy.get('#info1').should('not.have.class', 'instructions')
        cy.get('#info1').should('have.class', 'hideIns')
        cy.get('#done1').should('not.have.class', 'hide')
        cy.get('#done1').should('have.class', 'show')
        cy.contains('Username Instructions').should('not.be.visible')
        cy.contains('Valid Username').should('be.visible')

        // email element check
        cy.get('#email').click().focused()
        cy.get('#email').focus()
        cy.get('#info2').should('have.class', 'instructions')
        cy.get('#info2').should('not.have.class', 'hideIns')
        cy.get('#done2').should('have.class', 'hide')
        cy.get('#done2').should('not.have.class', 'show')
        cy.contains('Email Instructions').should('be.visible')
        cy.contains('Valid Email').should('not.be.visible')

        cy.get('#email').type('mari')
        cy.get('#info2').should('have.class', 'instructions')
        cy.get('#info2').should('not.have.class', 'hideIns')
        cy.get('#done2').should('have.class', 'hide')
        cy.get('#done2').should('not.have.class', 'show')
        cy.contains('Email Instructions').should('be.visible')
        cy.contains('Valid Email').should('not.be.visible')

        cy.get('#email').clear().type('mari@email.com')
        cy.get('#info2').should('not.have.class', 'instructions')
        cy.get('#info2').should('have.class', 'hideIns')
        cy.get('#done2').should('not.have.class', 'hide')
        cy.get('#done2').should('have.class', 'show')
        cy.contains('Email Instructions').should('not.be.visible')
        cy.contains('Valid Email').should('be.visible')

        // password element check
        cy.get('#password').click().focused()
        cy.get('#password').focus()
        cy.get('#info3').should('have.class', 'instructions')
        cy.get('#info3').should('not.have.class', 'hideIns')
        cy.get('#done3').should('have.class', 'hide')
        cy.get('#done3').should('not.have.class', 'show')
        cy.contains('Password Instructions').should('be.visible')
        cy.contains('Valid Password').should('not.be.visible')

        cy.get('#password').type('qqq')
        cy.get('#info3').should('have.class', 'instructions')
        cy.get('#info3').should('not.have.class', 'hideIns')
        cy.get('#done3').should('have.class', 'hide')
        cy.get('#done3').should('not.have.class', 'show')
        cy.contains('Password Instructions').should('be.visible')
        cy.contains('Valid Password').should('not.be.visible')

        cy.get('#password').clear().type('Q!1qqqqq')
        cy.get('#info3').should('not.have.class', 'instructions')
        cy.get('#info3').should('have.class', 'hideIns')
        cy.get('#done3').should('not.have.class', 'hide')
        cy.get('#done3').should('have.class', 'show')
        cy.contains('Password Instructions').should('not.be.visible')
        cy.contains('Valid Password').should('be.visible')

        // confirm password element check
        cy.get('#confirm-password').click().focused()
        cy.get('#password').focus()
        cy.get('#done4').should('have.class', 'hide')
        cy.get('#done4').should('not.have.class', 'show')
        cy.contains('Password confirmed').should('not.be.visible')

        cy.get('#confirm-password').type('qqq')
        cy.get('#done4').should('have.class', 'hide')
        cy.get('#done4').should('not.have.class', 'show')
        cy.contains('Password confirmed').should('not.be.visible')

        cy.get('#confirm-password').clear().type('Q!1qqqqq')
        cy.get('#done4').should('not.have.class', 'hide')
        cy.get('#done4').should('have.class', 'show')
        cy.contains('Password confirmed').should('be.visible')

        // Select skills element check
        cy.get('#skills').focus()
        cy.get('#skills').children().first().should('have.text', 'Select...')
        cy.get('#info4').should('have.class', 'instructions')
        cy.get('#info4').should('not.have.class', 'hideIns')
        cy.get('#done5').should('have.class', 'hide')
        cy.get('#done5').should('not.have.class', 'show')
        cy.contains('Required, please select a skill').should('be.visible')
        cy.contains('A skill is selected').should('not.be.visible')

        cy.get('#skills').select('React')
        cy.get('#info4').should('not.have.class', 'instructions')
        cy.get('#info4').should('have.class', 'hideIns')
        cy.get('#done5').should('not.have.class', 'hide')
        cy.get('#done5').should('have.class', 'show')
        cy.contains('Required, please select a skill').should('not.be.visible')
        cy.contains('A skill is selected').should('be.visible')

        // correct inputs prepared to be submitted
        cy.get('[for="username"]')
        cy.get('#username').type('Mari').clear().type('Maria')
        cy.get('[for="email"]')
        cy.get('#email').clear().type('mari@email.com')
        cy.get('[for="password"]')
        cy.get('#password').clear().type('Q!1qqqqq')
        cy.get('[for="confirm-password"]')
        cy.get('#confirm-password').clear().type('Q!1qqqqq')
        cy.get('[for="skills"]')
        cy.get('#skills').select('Select...')
        cy.get('#skills').select('React')

        cy.get('#checkbox').check().uncheck()
        cy.get('.checkbox-lable')

        cy.get('form > :nth-child(5)').should('be.visible')
        cy.get('form > :nth-child(9)').should('be.visible')
        cy.get('form > :nth-child(13)').should('be.visible')
        cy.get('form > :nth-child(16)').should('be.visible')
        cy.get('form > :nth-child(20)').should('be.visible')

    }) 

    it("Checking form submit and navigation to To-Do page", () => {
        cy.visit('/')
        cy.contains('Subscription Form').should('be.visible')

        cy.get('#username').should('have.value', '')
        cy.get('#email').should('have.value', '')
        cy.get('#password').should('have.value', '')
        cy.get('#confirm-password').should('have.value', '')
        cy.get('#skills').should('have.value', 'Select...')
        cy.get('#skills').children().first().then(option1 => {expect(option1).to.be.selected})
        cy.get('#skills').children().first().should('have.text', 'Select...')
        cy.get('#checkbox').should('not.be.checked')

        cy.get('form > :nth-child(5)').should('not.be.visible')
        cy.get('form > :nth-child(9)').should('not.be.visible')
        cy.get('form > :nth-child(13)').should('not.be.visible')
        cy.get('form > :nth-child(16)').should('not.be.visible')
        cy.get('form > :nth-child(20)').should('not.be.visible')

        cy.contains('Valid Username').should('not.be.visible')
        cy.contains('Valid Email').should('not.be.visible')
        cy.contains('Valid Password').should('not.be.visible')
        cy.contains('Password confirmed').should('not.be.visible')
        cy.contains('A skill is selected').should('not.be.visible')

        cy.get('#info1').should('have.class', 'hideIns')
        cy.get('#done1').should('have.class', 'hide')
        cy.get('#info2').should('have.class', 'hideIns')
        cy.get('#done2').should('have.class', 'hide')
        cy.get('#info3').should('have.class', 'hideIns')
        cy.get('#done3').should('have.class', 'hide')
        cy.get('#done4').should('have.class', 'hide')
        cy.get('#info4').should('have.class', 'hideIns')
        cy.get('#done5').should('have.class', 'hide')

        cy.get('[for="username"]')
        cy.get('#username').type('Mari').clear().type('Maria')
        cy.get('[for="email"]')
        cy.get('#email').clear().type('mari@email.com')
        cy.get('[for="password"]')
        cy.get('#password').clear().type('Q!1qqqqq')
        cy.get('[for="confirm-password"]')
        cy.get('#confirm-password').clear().type('Q!1qqqqq')
        cy.get('[for="skills"]')
        cy.get('#skills').select('Select...')
        cy.get('#skills').select('React')

        cy.get('#checkbox').check().uncheck()
        cy.get('.checkbox-lable')

        cy.get('form > :nth-child(5)').should('be.visible')
        cy.get('form > :nth-child(9)').should('be.visible')
        cy.get('form > :nth-child(13)').should('be.visible')
        cy.get('form > :nth-child(16)').should('be.visible')
        cy.get('form > :nth-child(20)').should('be.visible')

        cy.contains('Valid Username').should('be.visible')
        cy.contains('Valid Email').should('be.visible')
        cy.contains('Valid Password').should('be.visible')
        cy.contains('Password confirmed').should('be.visible')
        cy.contains('A skill is selected').should('be.visible')

        cy.get('#info1').should('have.class', 'hideIns')
        cy.get('#done1').should('have.class', 'show')
        cy.get('#info2').should('have.class', 'hideIns')
        cy.get('#done2').should('have.class', 'show')
        cy.get('#info3').should('have.class', 'hideIns')
        cy.get('#done3').should('have.class', 'show')
        cy.get('#done4').should('have.class', 'show')
        cy.get('#info4').should('have.class', 'hideIns')
        cy.get('#done5').should('have.class', 'show')

        cy.get('.subscribe-btn').click()

        cy.get('#task').should('be.visible')
        cy.get('#timeinterval').should('be.visible')

        cy.visit('/')
        cy.get('#username').should('have.value', '')
        cy.get('#email').should('have.value', '')
        cy.get('#password').should('have.value', '')
        cy.get('#confirm-password').should('have.value', '')
        cy.get('#skills').should('have.value', 'Select...')
        cy.get('#skills').children().first().then(option1 => {expect(option1).to.be.selected})
        cy.get('#skills').children().first().should('have.text', 'Select...')
        cy.get('#checkbox').should('not.be.checked')

        cy.get('form > :nth-child(5)').should('not.be.visible')
        cy.get('form > :nth-child(9)').should('not.be.visible')
        cy.get('form > :nth-child(13)').should('not.be.visible')
        cy.get('form > :nth-child(16)').should('not.be.visible')
        cy.get('form > :nth-child(20)').should('not.be.visible')

        cy.contains('Valid Username').should('not.be.visible')
        cy.contains('Valid Email').should('not.be.visible')
        cy.contains('Valid Password').should('not.be.visible')
        cy.contains('Password confirmed').should('not.be.visible')
        cy.contains('A skill is selected').should('not.be.visible')

        cy.get('#info1').should('have.class', 'hideIns')
        cy.get('#done1').should('have.class', 'hide')
        cy.get('#info2').should('have.class', 'hideIns')
        cy.get('#done2').should('have.class', 'hide')
        cy.get('#info3').should('have.class', 'hideIns')
        cy.get('#done3').should('have.class', 'hide')
        cy.get('#done4').should('have.class', 'hide')
        cy.get('#info4').should('have.class', 'hideIns')
        cy.get('#done5').should('have.class', 'hide')
    }) 

    it.only("Checking that in navigation from subscription page to To-Do page logout button exists", () => {
        cy.visit('/')
        cy.contains('Subscription Form').should('be.visible')

        cy.get('#username').should('have.value', '')
        cy.get('#email').should('have.value', '')
        cy.get('#password').should('have.value', '')
        cy.get('#confirm-password').should('have.value', '')
        cy.get('#skills').should('have.value', 'Select...')
        cy.get('#skills').children().first().then(option1 => {expect(option1).to.be.selected})
        cy.get('#skills').children().first().should('have.text', 'Select...')
        cy.get('#checkbox').should('not.be.checked')

        cy.get('form > :nth-child(5)').should('not.be.visible')
        cy.get('form > :nth-child(9)').should('not.be.visible')
        cy.get('form > :nth-child(13)').should('not.be.visible')
        cy.get('form > :nth-child(16)').should('not.be.visible')
        cy.get('form > :nth-child(20)').should('not.be.visible')

        cy.contains('Valid Username').should('not.be.visible')
        cy.contains('Valid Email').should('not.be.visible')
        cy.contains('Valid Password').should('not.be.visible')
        cy.contains('Password confirmed').should('not.be.visible')
        cy.contains('A skill is selected').should('not.be.visible')

        cy.get('#info1').should('have.class', 'hideIns')
        cy.get('#done1').should('have.class', 'hide')
        cy.get('#info2').should('have.class', 'hideIns')
        cy.get('#done2').should('have.class', 'hide')
        cy.get('#info3').should('have.class', 'hideIns')
        cy.get('#done3').should('have.class', 'hide')
        cy.get('#done4').should('have.class', 'hide')
        cy.get('#info4').should('have.class', 'hideIns')
        cy.get('#done5').should('have.class', 'hide')

        cy.get('[for="username"]')
        cy.get('#username').type('Mari').clear().type('Maria')
        cy.get('[for="email"]')
        cy.get('#email').clear().type('mari@email.com')
        cy.get('[for="password"]')
        cy.get('#password').clear().type('Q!1qqqqq')
        cy.get('[for="confirm-password"]')
        cy.get('#confirm-password').clear().type('Q!1qqqqq')
        cy.get('[for="skills"]')
        cy.get('#skills').select('Select...')
        cy.get('#skills').select('React')

        cy.get('#checkbox').check().uncheck()
        cy.get('.checkbox-lable')

        cy.get('form > :nth-child(5)').should('be.visible')
        cy.get('form > :nth-child(9)').should('be.visible')
        cy.get('form > :nth-child(13)').should('be.visible')
        cy.get('form > :nth-child(16)').should('be.visible')
        cy.get('form > :nth-child(20)').should('be.visible')

        cy.contains('Valid Username').should('be.visible')
        cy.contains('Valid Email').should('be.visible')
        cy.contains('Valid Password').should('be.visible')
        cy.contains('Password confirmed').should('be.visible')
        cy.contains('A skill is selected').should('be.visible')

        cy.get('#info1').should('have.class', 'hideIns')
        cy.get('#done1').should('have.class', 'show')
        cy.get('#info2').should('have.class', 'hideIns')
        cy.get('#done2').should('have.class', 'show')
        cy.get('#info3').should('have.class', 'hideIns')
        cy.get('#done3').should('have.class', 'show')
        cy.get('#done4').should('have.class', 'show')
        cy.get('#info4').should('have.class', 'hideIns')
        cy.get('#done5').should('have.class', 'show')

        cy.get('.subscribe-btn').click()

        cy.get('#task').should('be.visible')
        cy.get('#timeinterval').should('be.visible')

        cy.get('.logout').should('be.visible')
        cy.get('.logout').should('have.text', 'Log out')
        cy.get('.logout').click()
        cy.contains('Subscription Form').should('be.visible')
    }) 
})

